import React, { Fragment } from "react";
import PropTypes from "prop-types";
import Typography from "@material-ui/core/Typography";
import { withStyles } from "@material-ui/core/styles";
import CssBaseline from "@material-ui/core/CssBaseline";
import Paper from "@material-ui/core/Paper";
import Button from "@material-ui/core/Button";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
import ListItemText from "@material-ui/core/ListItemText";
import ListSubheader from "@material-ui/core/ListSubheader";
import SenderDetail from "../SenderDetail";

const styles = theme => ({
  text: {
    paddingTop: theme.spacing.unit * 2,
    paddingLeft: theme.spacing.unit * 2,
    paddingRight: theme.spacing.unit * 2
  },
  paper: {
    paddingBottom: 50
  },
  list: {
    marginBottom: theme.spacing.unit * 2,
    width: "100%",
    minWidth: 1020,
    backgroundColor: theme.palette.background.paper,
    position: "relative",
    overflow: "auto",
    maxHeight: 500
  },
  subHeader: {
    backgroundColor: theme.palette.background.paper
  },
  button: {
    margin: theme.spacing.unit
  },
  selected: {
    color: "green",
    background: "red"
  }
});

const messages = [
  {
    id: 1,
    primary: "Toilet Repair",
    secondary:
      "Could you give me more info on what you need done?",
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: false
  },
  {
    id: 2,
    primary: "I can fix your toilet",
    secondary: `It would be an easy fix. It won't cost as much as you expect. Let me know if you're intrested in me working for you.`,
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: false
  },
  {
    id: 3,
    primary: "AC Unit Repair- Auto",
    secondary:
      "I can do it. Call me. 321-122-4022",
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: false
  },
  {
    id: 4,
    primary: "Thermostat Fix",
    secondary: "I would do it for you, but it's an easy fix to save yourself some money. Google it!",
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: false
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: false
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: true
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://i2.wp.com/www.naturallysensible.com/wp-content/uploads/2017/10/login-user-icon.png?resize=200%2C200&ssl=1",
    read: true
  }
];

function NotificationList(props) {
  const { classes } = props;
  return (
    <React.Fragment>
      <CssBaseline />
      <Paper square className={classes.paper}>
        <List className={classes.list}>
          {messages.map(({ id, primary, secondary, person, read }) => (
            <Fragment key={id}>
              <ListSubheader className={classes.subHeader}>Today</ListSubheader>
              <ListItem button>
                <SenderDetail person={person} />
                <ListItemText
                  disableTypography
                  primary={
                    <Typography>{read ? primary : <b>{primary}</b>}</Typography>
                  }
                  secondary={secondary}
                />
                {read ? (
                  <React.Fragment />
                ) : (
                  <React.Fragment>
                    <Button
                      variant="outlined"
                      color="primary"
                      className={classes.button}
                    >
                      Accept
                    </Button>
                    <Button
                      variant="outlined"
                      color="secondary"
                      className={classes.button}
                    >
                      Reject
                    </Button>
                  </React.Fragment>
                )}
              </ListItem>
            </Fragment>
          ))}
        </List>
      </Paper>
    </React.Fragment>
  );
}

NotificationList.propTypes = {
  classes: PropTypes.object.isRequired
};

export default withStyles(styles)(NotificationList);
